include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - avoid_unnecessary_containers

analyzer:
  errors:
    info: ignore
    hint: ignore
